export const queryKeys = {
  patients: { all: ["patients"] as const, list: (filters: Readonly<Record<string, string>> = {}) => ["patients", "list", filters] as const, detail: (id: string) => ["patients", "detail", id] as const },
  samples: { all: ["samples"] as const }, tests: { all: ["tests"] as const }, reports: { all: ["reports"] as const, detail: (id: string) => ["reports", id] as const, templates: ["reports", "templates"] as const },
  dashboard: { all: ["dashboard"] as const, stats: () => ["dashboard", "stats"] as const, testVolume: () => ["dashboard", "test-volume"] as const, departments: () => ["dashboard", "departments"] as const, sampleStatistics: () => ["dashboard", "sample-statistics"] as const, revenue: () => ["dashboard", "revenue"] as const, turnaround: () => ["dashboard", "turnaround"] as const, activity: () => ["dashboard", "activity"] as const, pendingWork: () => ["dashboard", "pending-work"] as const, criticalResults: () => ["dashboard", "critical-results"] as const },
  doctors: { all: ["doctors"] as const, detail: (id: string) => ["doctors", id] as const }, suppliers: { all: ["suppliers"] as const, detail: (id: string) => ["suppliers", id] as const }, users: { all: ["users"] as const, detail: (id: string) => ["users", id] as const },
  qc: { all: ["qc"] as const, dashboard: () => ["qc", "dashboard"] as const, runs: (filters: Readonly<Record<string, unknown>> = {}) => ["qc", "runs", filters] as const, parameters: () => ["qc", "parameters"] as const, violations: () => ["qc", "violations"] as const, chart: (parameterId: string) => ["qc", "chart", parameterId] as const },
  instruments: { all: ["instruments"] as const, list: (filters: Readonly<Record<string, unknown>> = {}) => ["instruments", "list", filters] as const, detail: (id: string) => ["instruments", "detail", id] as const },
  analyzer: { all: ["analyzer"] as const, status: (instrumentId?: string) => ["analyzer", "status", instrumentId] as const, results: () => ["analyzer", "results"] as const, orders: () => ["analyzer", "orders"] as const, errors: () => ["analyzer", "errors"] as const },
  settings: { all: ["settings"] as const, laboratory: () => ["settings", "laboratory"] as const, report: () => ["settings", "report"] as const, referenceRanges: () => ["settings", "reference-ranges"] as const, units: () => ["settings", "units"] as const, notifications: () => ["settings", "notifications"] as const, system: () => ["settings", "system"] as const },
  profile: { all: ["profile"] as const, me: () => ["profile", "me"] as const },
} as const;
