"use client";
import { Activity, Building2, CalendarDays, ClipboardList, Droplets, FlaskConical, Gauge, LayoutDashboard, Microscope, Package, ReceiptText, Settings, ShieldCheck, Stethoscope, TestTube2, Users, X } from "lucide-react";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { authService } from "@/lib/auth/auth-service";
import type { LucideIcon } from "lucide-react";

type Item = Readonly<{ label: string; href: string; icon: LucideIcon }>;
const groups: readonly Readonly<{ label: string; items: readonly Item[] }>[] = [
    { label: "Overview", items: [{ label: "Dashboard", href: "/dashboard", icon: LayoutDashboard }] },
    { label: "Laboratory", items: [{ label: "Patients", href: "/patients", icon: Users }, { label: "Samples", href: "/samples", icon: TestTube2 }, { label: "Tests", href: "/tests", icon: ClipboardList }, { label: "Hematology", href: "/hematology", icon: Droplets }, { label: "Biochemistry", href: "/biochemistry", icon: FlaskConical }, { label: "Urine Analysis", href: "/urine-analysis", icon: Activity }, { label: "Electrolytes", href: "/electrolytes", icon: Gauge }] },
    { label: "Reporting", items: [{ label: "Reports", href: "/reports", icon: ReceiptText }] },
    { label: "Operations", items: [{ label: "Instruments", href: "/instruments", icon: Activity }, { label: "Quality Control", href: "/quality-control", icon: ShieldCheck }, { label: "Suppliers", href: "/suppliers", icon: Package }, { label: "Billing", href: "/billing", icon: ReceiptText }, { label: "Appointments", href: "/appointments", icon: CalendarDays }] },
    { label: "Administration", items: [{ label: "Franchises", href: "/franchises", icon: Building2 }, { label: "Doctors Directory", href: "/doctors", icon: Stethoscope }, { label: "Pathologist", href: "/pathologists", icon: Microscope }, { label: "Technician", href: "/technicians", icon: TestTube2 }, { label: "User Management", href: "/users", icon: Users }, { label: "Settings", href: "/settings", icon: Settings }] },
];

export function Sidebar({ mobileOpen, onClose }: Readonly<{ mobileOpen: boolean; onClose: () => void }>) {
    const pathname = usePathname(); const router = useRouter(); const logout = () => { authService.logout(); router.replace("/login"); };
    return <><button onClick={onClose} className={`fixed inset-0 z-30 bg-slate-950/30 lg:hidden ${mobileOpen ? "block" : "hidden"}`} aria-label="Close navigation" /><aside className={`fixed inset-y-0 left-0 z-40 flex w-[268px] flex-col border-r bg-surface px-3 py-5 transition-transform lg:translate-x-0 ${mobileOpen ? "translate-x-0" : "-translate-x-full"}`}><div className="mb-8 flex items-center justify-between px-3"><Link href="/dashboard" className="flex items-center gap-3"><div className="grid size-9 place-items-center rounded-xl bg-[#176b87] text-white"><FlaskConical size={20} /></div><div><p className="text-sm font-bold tracking-tight">BL Dignostic LIMS</p><p className="text-[11px] text-[color:var(--muted)]">Laboratory workspace</p></div></Link><button className="p-1 lg:hidden" onClick={onClose}><X size={20} /></button></div><nav className="min-h-0 flex-1 overflow-y-auto">{groups.map((group) => <div key={group.label} className="mb-5"><p className="mb-1 px-3 text-[10px] font-bold uppercase tracking-[0.12em] text-[color:var(--muted)]">{group.label}</p>{group.items.map(({ label, href, icon: Icon }) => <Link onClick={onClose} key={href} href={href} className={`mb-0.5 flex items-center gap-3 rounded-lg px-3 py-2 text-sm transition ${pathname === href ? "bg-[#e8f4f7] font-semibold text-[#176b87]" : "text-[color:var(--muted)] hover:bg-[#f4f7f8] hover:text-foreground"}`}><Icon size={17} />{label}</Link>)}</div>)}</nav><div className="border-t pt-3"><Link href="/profile" className={`flex items-center gap-3 rounded-lg px-3 py-2 text-sm ${pathname === "/profile" ? "bg-[#e8f4f7] text-[#176b87]" : "text-[color:var(--muted)]"}`}>{/* profile button */}<div className="grid size-6 place-items-center rounded-full bg-[#dbeef3] text-[10px] font-bold text-[#176b87]">AR</div>Profile</Link><button onClick={logout} className="flex w-full items-center gap-3 rounded-lg px-3 py-2 text-sm text-[color:var(--muted)] hover:bg-[#f4f7f8]"><X size={17} />Logout</button></div></aside></>;
}
