"use client";
import { Field, Form, Formik } from "formik";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { Printer } from "lucide-react";
import { PageHeader, StatusBadge } from "@/components/ui/page";
import { useAppointment, useAppointments, useCreateAppointment, useCreateInvoice, useInvoice, useInvoices } from "@/features/operations/hooks";
import type { Appointment, Invoice } from "@/types/domain";
export function OperationsManager({ kind, path }: Readonly<{ kind: "appointments" | "billing"; path: readonly string[] }>) {
    const router = useRouter(); const isAppointment = kind === "appointments"; const appointments = useAppointments(); const invoices = useInvoices(); const appointment = useAppointment(path[0] ?? ""); const invoice = useInvoice(path[0] ?? ""); const createAppointment = useCreateAppointment(); const createInvoice = useCreateInvoice(); const list = isAppointment ? appointments.data : invoices.data; if (!path.length) return <><PageHeader title={isAppointment ? "Appointments" : "Billing"} description={isAppointment ? "Coordinate patient visits and consultations." : "Manage invoices, payments, and laboratory charges."} action={<Link href={`/${kind}/new`} className="rounded-xl bg-[#176b87] px-4 py-2.5 text-sm font-semibold text-white">New {isAppointment ? "appointment" : "invoice"}</Link>} /><div className="overflow-x-auto border-t pt-4"><table className="w-full min-w-[700px] text-left text-sm"><thead className="border-b text-xs uppercase text-[color:var(--muted)]"><tr><th className="pb-3">{isAppointment ? "Patient" : "Bill number"}</th><th className="pb-3">{isAppointment ? "Date / time" : "Patient"}</th><th className="pb-3">Status</th><th /></tr></thead><tbody>{(list ?? []).map((row) => <tr className="border-b" key={row.id}><td className="py-4 font-semibold">{"billNumber" in row ? row.billNumber : row.patientId === "pat-01" ? "Maya Srinivasan" : row.patientId}</td><td className="py-4">{"billDate" in row ? row.patientId : `${row.date} · ${row.time}`}</td><td className="py-4"><StatusBadge tone={("paymentStatus" in row ? row.paymentStatus === "Paid" : row.status === "Upcoming") ? "success" : "warning"}>{"paymentStatus" in row ? row.paymentStatus : row.status}</StatusBadge></td><td className="py-4 text-right"><Link href={`/${kind}/${row.id}`} className="text-xs font-semibold text-[#176b87]">View</Link></td></tr>)}</tbody></table></div></>;
    if (path[0] === "new") { const initial = isAppointment ? { patientId: "pat-01", doctorId: "doc-01", date: "2026-08-23", time: "10:30", type: "Consultation", status: "Upcoming", appointmentLink: "", createdBy: "Dr. Ananya Rao" } : { billNumber: `INV-${Date.now().toString().slice(-6)}`, patientId: "pat-01", doctorId: "doc-01", billDate: "2026-08-22", items: [{ description: "CBC", quantity: 1, mrp: 450 }], discount: 0, sgst: 22.5, cgst: 22.5, total: 495, paymentStatus: "Pending", addedBy: "Dr. Ananya Rao" }; return <><PageHeader title={`New ${isAppointment ? "appointment" : "invoice"}`} description="Save this operational record." /><Formik initialValues={initial} onSubmit={(values) => (isAppointment ? createAppointment.mutateAsync(values as Omit<Appointment, "id">) : createInvoice.mutateAsync(values as Omit<Invoice, "id">)).then(() => router.push(`/${kind}`))}><Form className="grid gap-5 sm:grid-cols-2">{Object.keys(initial).filter((key) => key !== "items").map((key) => <div key={key}><label className="mb-2 block text-sm font-medium capitalize">{key}</label><Field name={key} className="w-full rounded-xl border bg-surface px-3 py-2.5 text-sm" /></div>)}<button className="w-fit rounded-xl bg-[#176b87] px-5 py-2.5 text-sm font-semibold text-white">Save</button></Form></Formik></>; }
    const detail = isAppointment ? appointment.data : invoice.data; if (!detail) return <p className="text-sm text-[color:var(--muted)]">Loading…</p>; if ("billNumber" in detail) return <><PageHeader title={detail.billNumber} description="Professional invoice preview." action={<button onClick={() => window.print()} className="rounded-xl border p-2"><Printer size={17} /></button>} /><article className="mx-auto max-w-3xl border bg-surface p-7 print:border-0"><header className="flex justify-between border-b pb-5"><div><p className="text-xl font-bold text-[#176b87]">BLDignostics LIMS</p><p className="text-xs text-[color:var(--muted)]">Tax invoice</p></div><StatusBadge tone="success">{detail.paymentStatus}</StatusBadge></header><div className="grid grid-cols-2 gap-4 py-5 text-sm"><p>Patient<br /><b>{detail.patientId}</b></p><p>Doctor<br /><b>{detail.doctorId}</b></p><p>Invoice date<br /><b>{detail.billDate}</b></p><p>Added by<br /><b>{detail.addedBy}</b></p></div><table className="w-full text-left text-sm"><thead><tr className="border-b"><th className="pb-3">Item</th><th>Qty</th><th>MRP</th></tr></thead><tbody>{detail.items.map((item) => <tr className="border-b" key={item.description}><td className="py-3">{item.description}</td><td>{item.quantity}</td><td>₹{item.mrp}</td></tr>)}</tbody></table><div className="ml-auto mt-5 max-w-xs space-y-2 text-sm"><p className="flex justify-between"><span>Discount</span><span>₹{detail.discount}</span></p><p className="flex justify-between"><span>SGST + CGST</span><span>₹{detail.sgst + detail.cgst}</span></p><p className="flex justify-between border-t pt-2 text-base font-bold"><span>Total</span><span>₹{detail.total}</span></p></div></article></>; return <><PageHeader title="Appointment detail" description="Patient consultation appointment." /><dl className="grid gap-px rounded-xl border bg-[color:var(--line)] sm:grid-cols-2">{Object.entries(detail).map(([key, value]) => <div className="bg-surface p-4" key={key}><dt className="text-xs text-[color:var(--muted)]">{key}</dt><dd className="mt-1 text-sm font-medium">{String(value)}</dd></div>)}</dl></>;
}
